#ifndef ADVANCED_OPTIMIZATION_METHODS_DIJKSTRA_HPP
#define ADVANCED_OPTIMIZATION_METHODS_DIJKSTRA_HPP

template<typename Distance>
class Dijkstra {};

#endif // ADVANCED_OPTIMIZATION_METHODS_DIJKSTRA_HPP
